# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNOcCOpqZ_J503Q7eUo64m9A1wSqQdVQ
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request
from flask import jsonify
from flask import Flask
import random as rk

app = Flask(__name__)
run_with_ngrok(app)

dicionario = {
    "name": "Anderson",
    "surname": "Carvalho",
    "idade": 32,
    "Nome": "Joao",
    "Surname": "Silva",
    "Idade": 19,
    "Nome": "Maria",
    "Surname": "Aparecida",
    "Idade": 20
}

@app.route("/input")

def home():
  return jsonify(d)

@app.route('/output', methods=['GET', 'POST'])
def predJson():
  pred = r.choice(['positive', 'negative'])
  nd = d
  nd['prediction'] = pred
  return jsonify(nd)

app.run()